# Generated by Django 4.2.21 on 2025-05-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
