# Generated by Django 4.2.21 on 2025-05-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_label', models.CharField(blank=True, max_length=255, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('time_spent', models.DurationField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='daily_tasks.dailytodo')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus_tracker.topic')),
            ],
        ),
    ]
